import { Campaign, Character } from "ddtools-types";

export const ABILITIES = ["str", "dex", "con", "int", "wis", "cha"] as const;

export const SKILLS = [
  "acrobatics",
  "animal handling",
  "arcana",
  "athletics",
  "deception",
  "history",
  "insight",
  "intimidation",
  "investigation",
  "medicine",
  "nature",
  "perception",
  "performance",
  "persuasion",
  "religion",
  "sleight of Hand",
  "stealth",
  "survival",
] as const;

export const SIZES = [
  "tiny",
  "small",
  "medium",
  "large",
  "huge",
  "gargantuan",
] as const;

export const ALIGNMENTS = [
  "lawful good",
  "neutral good",
  "chaotic good",
  "lawful neutral",
  "true neutral",
  "chaotic neutral",
  "lawful evil",
  "neutral evil",
  "chaotic evil",
] as const;

export const DAMAGE_TYPES = [
  "piercing",
  "slashing",
  "bludgeoning",
  "acid",
  "cold",
  "fire",
  "force",
  "lightning",
  "necrotic",
  "posion",
  "psychic",
  "radiant",
  "thunder",
] as const;

export const CONDITIONS = [
  "blinded",
  "charmed",
  "deafened",
  "exhaustion",
  "frightened",
  "grappled",
  "incapacitated",
  "invisible",
  "necrotic",
  "paralyzed",
  "petrified",
  "poisoned",
  "prone",
  "restrained",
  "stunned",
  "unconscious",
] as const;

export const SENSES = [
  "blindsight",
  "darkvision",
  "tremorsense",
  "truesight",
] as const;

export const ITEM_TYPES = [
  "$",
  "A",
  "AF",
  "AIR",
  "AT",
  "EM",
  "EXP",
  "FD",
  "G",
  "GS",
  "GV",
  "HA",
  "INS",
  "LA",
  "M",
  "MA",
  "MNT",
  "MR",
  "OTH",
  "P",
  "R",
  "RD",
  "RG",
  "S",
  "SC",
  "SCF",
  "SHP",
  "T",
  "TAH",
  "TG",
  "VEH",
  "WD",
] as const;

export const SPELL_COMPONENTS = ["v", "s", "m"] as const;

export const RARITIES = [
  "rare",
  "uncommon",
  "very rare",
  "legendary",
  "artifact",
  "common",
  "none",
  "unknown",
  "unknown (magic)",
  "varies",
] as const;

export const testCampaign: Campaign = {
  name: "Test Campaign",
  mode: "out-of-combat",
  createdAt: new Date().getTime(),
  color: "green",
  dmUserIds: ["123123124123123"],
  description: "lorem ipsum dolor sit amet",
};

export const testCharacter: Character = {
  xp: 0,
  race: { name: "Human" },
  classes: [
    {
      name: "Fighter",
      level: 3,
    },
  ],
  alignment: "lawful good",
  proficiencyBonus: 2,
  hasInspiration: false,
  hitDice: [
    {
      count: 3,
      sides: 8,
    },
  ],
  deathSaves: {
    successes: 0,
    failures: 0,
  },
  physical: {
    age: 20,
    eyes: "blue",
    hair: "black",
    skin: "white",
    height: 120,
    weight: 140,
    description: "Wow so handsome",
  },
  personality: {
    traits: [],
    ideals: [],
    bonds: [],
    flaws: [],
    backstory: "",
  },
  feats: [],
  weaponProficiencies: [],
  armorProficiencies: [],
  toolProficiencies: [],
  weapons: [],
  equipment: [],
  treasure: {
    platinum: 0,
    gold: 0,
    silver: 0,
    copper: 0,
  },
  name: "Nil Agosto",
  size: "small",
  speed: {
    walking: 0,
    climbing: 0,
    swimming: 0,
    flying: 0,
    burrowing: 0,
  },
  abilityScores: {
    cha: 12,
    con: 16,
    dex: 14,
    int: 11,
    str: 20,
    wis: 12,
  },
  hitPoints: {
    current: 26,
    temporary: 0,
    max: 30,
  },
  armorClass: 0,
  passivePerception: 0,
  skills: {
    acrobatics: { isProficient: false, isExpertise: false },
    "animal handling": { isProficient: false, isExpertise: false },
    arcana: { isProficient: false, isExpertise: false },
    athletics: { isProficient: false, isExpertise: false },
    deception: { isProficient: false, isExpertise: false },
    history: { isProficient: false, isExpertise: false },
    insight: { isProficient: false, isExpertise: false },
    intimidation: { isProficient: false, isExpertise: false },
    investigation: { isProficient: false, isExpertise: false },
    medicine: { isProficient: false, isExpertise: false },
    nature: { isProficient: false, isExpertise: false },
    perception: { isProficient: false, isExpertise: false },
    performance: { isProficient: false, isExpertise: false },
    persuasion: { isProficient: false, isExpertise: false },
    religion: { isProficient: false, isExpertise: false },
    "sleight of Hand": { isProficient: false, isExpertise: false },
    stealth: { isProficient: false, isExpertise: false },
    survival: { isProficient: false, isExpertise: false },
  },
  savingThrows: {
    cha: { isProficient: false },
    con: { isProficient: false },
    dex: { isProficient: false },
    int: { isProficient: false },
    str: { isProficient: false },
    wis: { isProficient: false },
  },
  languages: [],
  senses: {
    blindsight: 0,
    darkvision: 0,
    tremorsense: 0,
    truesight: 0,
  },
  conditions: [],
  conditionImmunities: [],
  damageImmunities: [],
  damageResistances: [],
  damageVulnerabilities: [],
  tags: [],
  ownerUserId: "123123124123123",
  sharedWith: [],
  createdAt: new Date().getTime(),
  isActive: true,
};

const defaultSkills = SKILLS.reduce(
  (obj, skill) => ({
    ...obj,
    [skill]: { isProficient: false, isExpertise: false, miscModifier: 0 },
  }),
  {},
) as Character["skills"];

const defaultSavingThrows = SKILLS.reduce(
  (obj, skill) => ({
    ...obj,
    [skill]: { isProficient: false, miscModifier: 0 },
  }),
  {},
) as Character["savingThrows"];

export const emptyCharacter: Character = {
  xp: 0,
  race: undefined!,
  classes: [],
  alignment: "true neutral",
  proficiencyBonus: 0,
  hasInspiration: false,
  hitDice: [],
  deathSaves: {
    successes: 0,
    failures: 0,
  },
  physical: {
    age: 0,
    eyes: "",
    hair: "",
    skin: "",
    height: 0,
    weight: 0,
    description: "",
  },
  personality: {
    traits: [],
    ideals: [],
    bonds: [],
    flaws: [],
    backstory: "",
  },
  feats: [],
  weaponProficiencies: [],
  armorProficiencies: [],
  toolProficiencies: [],
  weapons: [],
  equipment: [],
  treasure: {
    platinum: 0,
    gold: 0,
    silver: 0,
    copper: 0,
  },
  name: "",
  size: "tiny",
  speed: {
    walking: 0,
    climbing: 0,
    swimming: 0,
    flying: 0,
    burrowing: 0,
  },
  abilityScores: {
    cha: 0,
    str: 0,
    dex: 0,
    con: 0,
    int: 0,
    wis: 0,
  },
  hitPoints: {
    current: 0,
    temporary: 0,
    max: 0,
  },
  armorClass: 0,
  passivePerception: 0,
  skills: defaultSkills,
  savingThrows: defaultSavingThrows,
  languages: [],
  senses: {
    blindsight: 0,
    darkvision: 0,
    tremorsense: 0,
    truesight: 0,
  },
  conditions: [],
  conditionImmunities: [],
  damageImmunities: [],
  damageResistances: [],
  damageVulnerabilities: [],
  tags: [],
  ownerUserId: "",
  sharedWith: [],
  createdAt: 0,
  isActive: true,
};
